### ISSUE TITLE
Unable to build example project (android)

### ISSUE THREAD

**Issue by DipankurSuffescom** [googlemaps/react-native-navigation-sdk#359] opened 2024-11-22 13:04 UTC
#### Environment details

#OS type and version
MacOS : Sonoma (14.4.1)

# Library version and other environment information
@googlemaps/react-native-navigation-sdk: from the example project
react-native: "0.76.2"
Java Version : 17.0.9
Gradle : 8.11

#### Steps to reproduce

  1. Clone the repo.
  2. Follow setup instructions as in readme for react-native-navigation-sdk SDK and exmple project in it.
  3. Run "yarn android" or "npx react-native run-android".
  4. Build fails with : 
  
  * What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Cannot query the value of this provider because it has no value available. 

#### Code example

```
# Same code as in example project.
```

#### Stack trace
```
# info A dev server is already running for this project on port 8081.
info Installing the app...
13 actionable tasks: 3 executed, 10 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Cannot query the value of this provider because it has no value available.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Cannot query the value of this provider because it has no value available. * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 4s.
```

I tried downgrading gradle version. Removing gradle cache. removing and reinstalling android studio dependencies.

npx react-native doctor Output:
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies
 ✓ npm - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✓ Android SDK - Required for building and installing your app on Android

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   0
Warnings: 0

I was able to build and test with iOS just fine.

Thanks!

**Comment by jokerttu** [comment] 2024-11-25 09:48
Hi @DipankurSuffescom 
I was not able to reproduce this with clean clone.

```sh
rm -rf ~/.gradle/caches
yarn install
cd example/android
./gradlew clean
./gradlew build --stacktrace
```

Also try to open the android app in Android Studio and run gradle sync

**Comment by jokerttu** [comment] 2024-11-27 11:15
@DipankurSuffescom please close this issue if above instructions fixed the situation.

**Comment by DipankurSuffescom** [comment] 2024-12-02 12:43
@jokerttu Thanks for your response. I will check and get back to you ASAP.

**Comment by jokerttu** [comment] 2024-12-10 08:35
Closing the issue as no new info about the issue.

**Closed by jokerttu** 2024-12-10 08:35 UTC
Labels: status: investigating, type: bug
