### ISSUE TITLE
Stop sign support

### ISSUE THREAD

**Issue by tikotas** [googlemaps/react-native-navigation-sdk#334] opened 2024-11-11 12:10 UTC
**Is your feature request related to a problem? Please describe.**
Can you add logic to support stop signs in a future release?

 **Describe the solution you'd like**
I want the stop sign to appear the same way it does in the Google Maps app navigation.
![test_image](https://github.com/user-attachments/assets/41849ccc-3d97-431a-a1de-e230c343d80a)

**Comment by jokerttu** [comment] 2024-11-11 13:07
@tikotas thank you for your feature request!
Stop sign support is on our roadmap on features to implement.
Closing as duplicate of https://github.com/googlemaps/react-native-navigation-sdk/issues/261

**Closed by jokerttu** 2024-11-11 13:07 UTC
Labels: type: feature request
