### ISSUE TITLE
How to stop navigation

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#301] opened 2024-10-14 15:53 UTC
So our flow is like this.

1. You go to task screen where you see some details.
2. You then navigate to navigation where guidance automatically starts.
3. you can go back if you need some more details
4. during this time navigation is still active. We don't call clear or stop guidance here since we still want navigation to be active when user return to navigation screen.
5. in case you close and open the app again on Android, navigation starts giving you directions as well as show notifications with directions. Ios is completely silent. no gps is used. no notifications. no guidance.
6. When you manually navigate back to navigation screen, navigation is not active.(if you go to navigation screen, wait for navigation to start, go back and go to navigation screen again, you can see that navigation is still active from before)
Calling cleanup also returns this error 
```js
Possible Unhandled Promise Rejection (id: 11):
Error: Navigation session not initialized
```
so i guess navigation is not active even tho i'm getting guidance?

This behavior is very strange and differs between platforms. What is the recommended approach for this?

**Comment by ziga-hvalec** [comment] 2024-10-14 15:58
scratch that. On android navigation keeps on going even if you close the app. This is a bug. I can't stop navigation if user force closes the app.

**Comment by jokerttu** [comment] 2024-10-16 19:49
This is duplicate of #34

**Closed by jokerttu** 2024-10-16 19:49 UTC
Labels: type: question, triage me
